#include <string.h>
#include <mono-wasi/driver.h>
#include <mono/metadata/assembly.h>

// This symbol's implementation is generated during the build
const char* dotnet_wasi_getentrypointassemblyname();

// These are generated by EmitWasmBundleObjectFile
const char* dotnet_wasi_getbundledfile(const char* name, int* out_length);
void dotnet_wasi_registerbundledassemblies();

#ifdef WASI_AFTER_RUNTIME_LOADED_DECLARATIONS
// This is supplied from the MSBuild itemgroup @(WasiAfterRuntimeLoaded)
WASI_AFTER_RUNTIME_LOADED_DECLARATIONS
#endif

int main(int argc, char *argv[]) {
    dotnet_wasi_registerbundledassemblies();

    if (argc > 1 && !strcmp(argv[1], "debug"))
        mono_wasm_load_runtime("--debugger-agent=transport=wasi_socket,address=127.0.0.1:64000,loglevel=0", -1);
    else
        mono_wasm_load_runtime("", 0);

#ifdef WASI_AFTER_RUNTIME_LOADED_CALLS
    // This is supplied from the MSBuild itemgroup @(WasiAfterRuntimeLoaded)
    WASI_AFTER_RUNTIME_LOADED_CALLS
#endif

    // TODO: Consider passing through the args
    MonoArray* args = mono_wasm_string_array_new(0);
    void* entry_method_params[] = { args };

    MonoAssembly* assembly = mono_assembly_open(dotnet_wasi_getentrypointassemblyname(), NULL);
    MonoMethod* entry_method = mono_wasm_assembly_get_entry_point(assembly);
    MonoObject* out_exc = NULL;
    mono_wasm_invoke_method(entry_method, NULL, entry_method_params, &out_exc);

    // Note: if the return value isn't an int (e.g., it's async main, returning a Task)
    // then the following will result in an obscure error.
    // TODO: Handle all entrypoint method types
    // return mono_unbox_int(exit_code);
    return out_exc ? 1 : 0;
}
