#include <string.h>
#include <mono-wasi/driver.h>
#include <mono/metadata/assembly.h>
#include <mono/metadata/class.h>

// This symbol's implementation is generated during the build
const char* dotnet_wasi_getentrypointassemblyname();

// These are generated by EmitWasmBundleObjectFile
const char* dotnet_wasi_getbundledfile(const char* name, int* out_length);
void dotnet_wasi_registerbundledassemblies();

#ifdef WASI_AFTER_RUNTIME_LOADED_DECLARATIONS
// This is supplied from the MSBuild itemgroup @(WasiAfterRuntimeLoaded)
WASI_AFTER_RUNTIME_LOADED_DECLARATIONS
#endif

// Populated during first invocation of main(), which might be preinitialization
MonoMethod* entry_method;

int main() {
    if (!entry_method) {
        dotnet_wasi_registerbundledassemblies();
        mono_wasm_load_runtime("", 0);

        #ifdef WASI_AFTER_RUNTIME_LOADED_CALLS
            // This is supplied from the MSBuild itemgroup @(WasiAfterRuntimeLoaded)
            WASI_AFTER_RUNTIME_LOADED_CALLS
        #endif
        
        MonoAssembly* entry_assembly = mono_assembly_open(dotnet_wasi_getentrypointassemblyname(), NULL);
        entry_method = mono_wasm_assembly_get_entry_point(entry_assembly);
    }

    if (getenv("WASI_PREINITIALIZE_ONLY")) {
        // If there's a Preinitialize method on the entry class, invoke it
        MonoClass* entry_method_class = mono_method_get_class(entry_method);
        MonoMethod* entry_method_class_preinitialize = mono_class_get_method_from_name(entry_method_class, "Preinitialize", 0);
        MonoObject* out_exc = NULL;
        if (entry_method_class_preinitialize) {
            mono_wasm_invoke_method(entry_method_class_preinitialize, NULL, NULL, &out_exc);
        }
        return out_exc ? 1 : 0;
    } else {
        // TODO: Consider passing through the args
        MonoArray* args = mono_wasm_string_array_new(0);
        void* entry_method_params[] = { args };
        MonoObject* out_exc = NULL;
        mono_wasm_invoke_method(entry_method, NULL, entry_method_params, &out_exc);

        // Note: if the return value isn't an int (e.g., it's async main, returning a Task)
        // then the following will result in an obscure error.
        // TODO: Handle all entrypoint method types
        // return mono_unbox_int(exit_code);
        return out_exc ? 1 : 0;
    }
}
